---
title: "Explaining to myself selection & complementarity effects"
description: "...or more precisely, the Loreau & Hector partitioning."
author: "Angelos Amyntas"
draft: true
draft-mode: unlinked
date: 2025-08-28
categories: [complementarity, selection]
format: html
editor: visual
mainfont: constantia
fontcolor: rgb(48, 48, 18)
linkcolor: rgb(196,98,16)
backgroundcolor: rgb(247, 247, 239)
highlight-style: zenburn
bibliography: references.bib
---

## motivation

Descriptions of Loreau and Hector's (2001) partitioning of **net biodiversity effects** into **selection** and **complementarity effects**, are usually top-down. They start with the net difference in community-level yield from the expected community yield, based on monoculture performance, and then explain how this breaks down into the two main components, and how each of these components is calculated. It is a partitioning scheme after all, so this *whole-to-parts* perspective makes sense. That does not necessarily make it an easy way in. There is a higher cognitive load involved in unpacking complex concepts, relative to assembling them from simple parts. So I suspect that a bottom-up approach may be less demanding; we get to understand the fundamental quantities and what they represent, and only then do we figure out how they fit together.

So below is my attempt to do just that.

## parts to whole

The standard design of a biodiversity & ecosystem functioning experiment features monocultures of individual species and the same species grown in mixtures. The set up of the experiment is substitutive, in the sense that all experimental units start with the same amount of organisms. What this amount is, depends on the type of community examined; number of seeds for grassland communities, saplings for forest ones, cells for unicellular phytoplankton. So if monocultures are set up with 1000 cells per volume of water, four-species mixtures will have 250 cells per species. Also, all experimental units have the same amount of resources—more generally, they grow under the same conditions—which in the case of a field experiment is usually accomplished with a "common garden" design.

Single and multispecies communities are established, then harvested after a reasonable amount of time. The question is then, first, whether mixtures have a higher yield than monocultures and second, how that relates to individual species performance in mixtures relative to their monoculture. In other words, for every species $i$ in every mixture community $j$, we are interested in the yield of the species in the mixture $Y_i^j$ relative to its yield in the monoculture $M_i$. The ratio of the two is called relative yield:

$$RY_i^j =\frac{Y_i^j}{M_i}$$

Now recall that, due to the substitutive design of the experiment, in a mixture of N species, species $i$ will start with 1/N of its monoculture amount. Therefore, 1/N is also the null expectation for the species' relative yield, that is *relative to its monoculture yield not to the mixture's total yield*. So if the species' yield when cultured alone is 40 biomass units, its expected yield when it is cultured with three other species *and therefore starts with a quarter of its monoculture starting amount*, would be $\frac{1}{4} \cdot40$ biomass units.

Therefore, the observed difference of the relative yield from the null expectation is:

$$\Delta RY_i^j = \frac{Y_i^j}{M_i} - \frac{1}{N^j}$$ $\Delta RY_i^j$ is going to be zero if a species' performance in mixture $j$ is exactly what we would expect based on its monoculture performance. This would indicate that diversity *i.e.* growing in a mixture, has no influence on the performance of this particular species. If all species in all mixtures perform as expected based on their monocultures, then there are no discernible diversity effects, period.

Let us now consider deviations from that null expectation; a species' yield in a mixture can be higher than the null expectation, in which case $\Delta RY_i^j > 0$ or lower, so $\Delta RY_i^j < 0$. In practice, these are never going to be exactly zero because, even in the absence of diversity effects, there would be some variation in how much a species yields in each experimental unit. But a more ecologically interesting source of deviation is if some species are more acquisitive than others, taking up resources faster than their competitors. In that case, their $\Delta RY_i^j$ will be higher than that of other species in the community, *regardless of its sign*. If these species are also more efficient in their use of resources, they will be species with higher monoculture yield, $M_i$ relative to these other species. In other words, if both of these are true, for a focal mixture $j$ we expect a positive covariance between the different species yield deviations $\Delta RY_i^j$ and their respective yields in monocultures $M_i$.

$$\operatorname{cov}(\mathbf{M}^j, \boldsymbol{\Delta} \mathbf{RY}^j) > 0$$ where $\mathbf{M}^j$ is the vector of monoculture yields for all species in mixture $j$ and $\boldsymbol{\Delta} \mathbf{RY}^j$ is the vector of their deviations from the expected yield. It is also possible that species that are relatively productive on their own, *i.e.* good at using the available resources to produce biomass, are nevertheless not very competitive in the presence of other species. In that case, the covariance between monoculture yields and deviations from the expected yield would be negative.

Let's recap. Within a mixture, a species may yield more or less than what is expected based on its monoculture yield, indicating some influence of the presence of other species on its own productivity, or it may yield close to the null expectation, indicating a lack of such an influence. Then, the covariance between monoculture yields and deviations from the expected yield in a mixture can be positive if species that are productive alone also tend to outperform their competitors, and negative if they are less competitive, or close to zero if their monoculture yields are no indication of how they perform in the mixture.

Covariance is calculated as: $$\operatorname{cov}(\mathbf{M}^j, \boldsymbol{\Delta} \mathbf{RY}^j) = \frac{1}{N^j} \sum_{i=1}^{N^j} (M_i^j - \overline{M^j})(\Delta RY_i^j - \overline{\Delta RY^j})$$

Note that the sum here is divided by $N$ rather than $N-1$, which would be the conventional small-sample bias correction applied for example by the base R `cov()` function. The $N-1$ version gives an unbiased covariance *estimator*. Instead here we *calculate* covariance for the entire "population" i.e. all the species in this particular experimental unit.

By its mathematical definition, covariance is a per species quantity. We can multiply it again by $N^j$, the number of species that comprise the mixture, to get a community level quantity. This quantity is what @loreau2001 defined as the **selection effect**: $$SE^j = N^j \cdot \operatorname{cov}(\mathbf{M}^j, \boldsymbol{\Delta} \mathbf{RY}^j)$$

It expresses the extent to which community-level deviations from monoculture-based expectations are attributable to a covariance—positive or negative—between species-level deviations and their monoculture performance.

Now let us consider what is the average relative yield of the species in a mixture community $j$. If the average species in the mixture does better than expected by its monoculture, $\overline{\Delta RY^{j}}$ will be positive. It will be negative if it does worse, or close to zero if positive deviations tend to cancel out with negative ones. Now recall that $RY_i^j$ and $\Delta RY_i^j$ are proportional quantities. Similarly, $\overline{\Delta RY^{j}}$ gives us the average *proportional* deviation from the expected yield. $\overline{M^j}$ is the monoculture yield of the average species in community $j$. By multiplying the two, $\overline{\Delta RY^{j}} \cdot \overline{M^j}$, we get the average per-species gain or loss in yield due to diversity effects. The multiplication with $\overline{M^j}$ takes us from the proportional scale back to the raw yield scale. So if the monoculture yield of the average species is large, then a proportional change will lead to a large change in absolute terms. If the monoculture yield average is small, even large proportional changes will amount to a small change in yield. Multiplying again by $N^j$, we get the community-level change in yield that can be attributed to an increase or decrease in average species-level performance and is what @loreau2001 defined as the **complementarity effect**:

$$CE^j = N^j \cdot \overline{\Delta RY^{j}} \cdot \overline{M^j}$$

Together, the two terms give us the net difference in yield:

$$\Delta Y^j = N^j \cdot \operatorname{cov}(\mathbf{M}^j, \boldsymbol{\Delta} \mathbf{RY}^j) + N^j \cdot \overline{\Delta RY^{j}} \cdot \overline{M^j}$$

@loreau2001 call this the **net biodiversity effect** i.e.

$$NBE^j = SE^j + CE^j$$

```{r}
loreau_hector = function(
    M_i,                # vector of species yield in monoculture
    Y_i                 # vector of species yield in mixture
       ) {
  N = length(M_i)       # number of species in the mixture
  dRY = Y_i/M_i - 1/N   # deviation from expected relative yield of species i

  M_bar = mean(M_i)     # average yield across the monocultures of constituent species
  dRY_bar = mean(dRY)   # mean deviation

  CE = N * dRY_bar * M_bar                    # complementarity effect
  SE = sum((M_i - M_bar) * (dRY - dRY_bar))   # selection effect
  NE = CE + SE                                # net effect
  c(NE,CE,SE)
}
```
